### ISSUE TITLE
Should tcp_* with a block close the sockfd automatically ?

### ISSUE THREAD

**Issue by danghvu** [ronin-rb/ronin-support#61]
I think it comes normally for a block to close its operation automatically. For example

```
>> a = open('/etc/passwd'){|f| p f}
#<File:/etc/passwd>
=> #<File:/etc/passwd (closed)>
>> a.read()
IOError: closed stream [(ronin):13:in `read'
```

But tcp_\* does not close the connection thus it will remain until the end leaving the sockfd not to be reused.

```
>> s = tcp_connect('localhost',8080){|s| p s}
#<TCPSocket:fd 10>
=> #<TCPSocket:fd 10>
>> s = tcp_connect('localhost',8080){|s| p s}
#<TCPSocket:fd 11>
=> #<TCPSocket:fd 11>
```

btw, I also think `tcp_send` should return the data if the server return something instead of just return `true`

**Comment by postmodern** [comment]
All `*_session` methods have been combined into the `*_connect` methods in the [1.0.0 branch](https://github.com/ronin-rb/ronin-support/tree/1.0.0). Now when `*_connect` is passed a block it will close the connection once the block returns.
